name:                client-server-app
version:             0.1.0.0
github:              "hazurl/client-server-app"
license:             MIT
author:              "Hazurl"
copyright:           "2019 Hazurl"

extra-source-files:
- README.md

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/hazurl/client-server-app#readme>

dependencies:
- base >= 4.7 && < 5
- network
- bytestring

library:
  source-dirs: src

executables:
  client-server-app-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - client-server-app
